swagger: '2.0'
info:
  version: '1.0.0'
  title: 'API Transactions'
  description: 'API pour gérer les transactions et les comptes.'
host: 'api.com'
schemes:
  - https
basePath: '/v1'
produces:
  - application/json

paths:
  /users/{userId}/accounts:
    get:
      summary: 'Récupère la liste des comptes'
      parameters:
        - name: userId
          in: path
          description: 'ID utilisateur'
          required: true
          type: string
      responses:
        200:
          description: 'Liste des comptes'
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'

  /users/{userId}/accounts/{accountId}/transactions:
    get:
      summary: 'Récupère les transactions'
      parameters:
        - name: userId
          in: path
          description: "ID utilisateur"
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
      responses:
        200:
          description: 'Liste des transactions pour le compte spécifié'
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'

  /users/{userId}/accounts/{accountId}/transactions/{transactionId}:
    get:
      summary: 'Récupère les détails d''une transaction'
      parameters:
        - name: userId
          in: path
          description: "ID utilisateur"
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
        - name: transactionId
          in: path
          description: 'ID de la transaction'
          required: true
          type: string
      responses:
        200:
          description: 'Détails de la transaction'
          schema:
            $ref: '#/definitions/Transaction'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'

  /users/{userId}/accounts/{accountId}/transactions/{transactionId}/category:
    put:
      summary: 'Met à jour la catégorie d''une transaction'
      parameters:
        - name: userId
          in: path
          description: "ID utilisateur"
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
        - name: transactionId
          in: path
          description: 'ID de la transaction'
          required: true
          type: string
        - in: body
          name: body
          description: 'Nouvelle catégorie pour la transaction'
          schema:
            $ref: '#/definitions/Category'
      responses:
        200:
          description: 'Catégorie mise à jour avec succès'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'
    post:
      summary: 'Ajoute une catégorie à une transaction'
      parameters:
        - name: userId
          in: path
          description: "ID utilisateur"
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
        - name: transactionId
          in: path
          description: 'ID de la transaction'
          required: true
          type: string
        - in: body
          name: body
          description: 'Catégorie pour la transaction'
          schema:
            $ref: '#/definitions/Category'
      responses:
        201:
          description: 'Catégorie ajoutée avec succès'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'
    delete:
      summary: 'Supprime la catégorie d''une transaction'
      parameters:
        - name: userId
          in: path
          description: "ID utilisateur"
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
        - name: transactionId
          in: path
          description: 'ID de la transaction'
          required: true
          type: string
      responses:
        200:
          description: 'Catégorie supprimée avec succès'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'

  /users/{userId}/accounts/{accountId}/transactions/{transactionId}/note:
    put:
      summary: 'Met à jour la note d''une transaction'
      parameters:
        - name: userId
          in: path
          description: "ID utilisateur"
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
        - name: transactionId
          in: path
          description: 'ID de la transaction'
          required: true
          type: string
        - in: body
          name: body
          description: 'Nouvelle note pour la transaction'
          schema:
            $ref: '#/definitions/Note'
      responses:
        200:
          description: 'Note mise à jour avec succès'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'
    post:
      summary: 'Ajoute une note à une transaction'
      parameters:
        - name: userId
          in: path
          description: "ID utilisateur"
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
        - name: transactionId
          in: path
          description: 'ID de la transaction'
          required: true
          type: string
        - in: body
          name: body
          description: 'Note pour la transaction'
          schema:
            $ref: '#/definitions/Note'
      responses:
        201:
          description: 'Note ajoutée avec succès'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'
    delete:
      summary: 'Supprime la note d''une transaction'
      parameters:
        - name: userId
          in: path
          description: "ID utilisateur"
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
        - name: transactionId
          in: path
          description: 'ID de la transaction'
          required: true
          type: string
      responses:
        200:
          description: 'Note supprimée avec succès'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'

definitions:
  Account:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      balance:
        type: number
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      amount:
        type: number
      description:
        type: string
  Category:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
  Note:
    type: object
    properties:
      id:
        type: string
      content:
        type: string
