swagger: '2.0'
info:
  version: '1.0.0'
  title: 'API Transactions'
  description: 'API pour gérer les transactions et les comptes.'
host: 'api.com'
schemes:
  - https
basePath: '/v1'
produces:
  - application/json

paths:
  /users/{userId}/accounts:
    get:
      summary: 'Récupère la liste des comptes '
      parameters:
        - name: userId
          in: path
          description: 'IDutilisateur'
          required: true
          type: string
      responses:
        200:
          description: 'Liste des comptes '
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'
  
  /users/{userId}/accounts/{accountId}/transactions:
    get:
      summary: 'Récupère les transactions '
      parameters:
        - name: userId
          in: path
          description: 'IDutilisateur'
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
      responses:
        200:
          description: 'Liste des transactions pour le compte spécifié'
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'
  
  /users/{userId}/accounts/{accountId}/transactions/{transactionId}:
    get:
      summary: 'Récupère les détails '
      parameters:
        - name: userId
          in: path
          description: 'ID de l\utilisateur'
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
        - name: transactionId
          in: path
          description: 'ID de la transaction'
          required: true
          type: string
      responses:
        200:
          description: 'Détails de la transaction'
          schema:
            $ref: '#/definitions/Transaction'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'
  
  /users/{userId}/accounts/{accountId}/transactions/{transactionId}/category:
    put:
      summary: 'Met à jour la catégorie d\une transaction'
      parameters:
        - name: userId
          in: path
          description: 'ID de l\utilisateur'
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
        - name: transactionId
          in: path
          description: 'ID de la transaction'
          required: true
          type: string
        - in: body
          name: body
          description: 'Nouvelle catégorie pour la transaction'
          schema:
            $ref: '#/definitions/Category'
      responses:
        200:
          description: 'Catégorie mise à jour avec succès'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'

  /users/{userId}/accounts/{accountId}/transactions/{transactionId}/note:
    put:
      summary: 'Ajoute/modifie une note pour une transaction'
      parameters:
        - name: userId
          in: path
          description: 'ID de l\utilisateur'
          required: true
          type: string
        - name: accountId
          in: path
          description: 'ID du compte'
          required: true
          type: string
        - name: transactionId
          in: path
          description: 'ID de la transaction'
          required: true
          type: string
        - in: body
          name: body
          description: 'Nouvelle note pour la transaction'
          schema:
            $ref: '#/definitions/Note'
      responses:
        200:
          description: 'Note mise à jour avec succès'
        400:
          description: 'Invalid Fields'
        500:
          description: 'Internal Server Error'


definitions:
  Account:
    type: object
    properties:
      id:
        type: string
      userId:
        type: string
      name:
        type: string
      balance:
        type: string
      currency:
        type: string

  Transaction:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: string
      balance:
        type: string
      category:          
        type: string     
      note:              
        type: string     


     

  Category:
    type: object
    properties:
      category:
        type: string
  
  Note:
    type: object
    properties:
      note:
        type: string
  
 
